---
title: "Capture data Table 1"
output: html_notebook
---


```{r echo=FALSE, message=FALSE}
rm(list=ls())
ifelse(Sys.info()[1] == 'Linux',
       source('~/Documents/R/tools/TomosFunctions.R'),
       source('~/R/tools/TomosFunctions.R'))

#library(readxl)
library(dplyr)
library(ggplot2)
library(lubridate)
library(tidyverse)
```

This notebook creates Table 1. It brings in the file IDvsUDs.csv, which was created by HR_analylsis_GPS_LC_newtags_2019-10-.Rmd, which also used another file all_sample_summary_size_2018-07-24.csv. See each of these files for details. 

```{r}

data1 <- read.csv(file = "data/IDvsUDs.csv")

data1 %>% mutate(ID.f = as.factor(ArgosID),
                 n.days = n.days.GPS,
                 n.relocations = n.relocations.all.GPS,
                 n.day = n.day.all.GPS,
                 n.night = n.night.all.GPS) %>%
  dplyr::select(ID.f, Capture_Date, n.days, n.relocations,
                n.day, n.night, Sex, Mass_kg, SCL_cm,
                period) -> data2

head(data2)
```

Then compute some statistics that were needed in the text.

```{r}
mean(data2$SCL_cm)
SE(data2$SCL_cm)
min(data2$SCL_cm)
max(data2$SCL_cm)

mean(data2$Mass_kg)
SE(data2$Mass_kg)
min(data2$Mass_kg)
max(data2$Mass_kg)

mean(data2$n.days)
SE(data2$n.days)
min(data2$n.days)
max(data2$n.days)
```

Look at SCL, mass, and number of transmission days between two periods.

```{r}
lm_SCL <- lm(SCL_cm ~ period, data = data2)
summary(lm_SCL)
```

```{r}
lm_Mass <- lm(Mass_kg ~ period, data = data2)
summary(lm_Mass)
```

```{r}
lm_ndays <- lm(n.days ~ period, data = data2)
summary(lm_ndays)
```


<!-- Split statistics into pre and post periods: -->
<!-- ```{r} -->
<!-- data2 %>% mutate(period.f = as.factor(period)) %>% -->
<!--   group_by(period.f) %>% summarise(mean.n.days = mean(n.days), -->
<!--                                    SE.n.days = SE(n.days), -->
<!--                                    mean.n.relocations = mean(n.relocations), -->
<!--                                    SE.n.relocations = SE(n.relocations), -->
<!--                                    #mean.n.relocations.all = mean(n.relocations.all), -->
<!--                                    #SE.n.relocations.all = SE(n.relocations.all), -->
<!--                                    mean.n.day = mean(n.day), -->
<!--                                    SE.n.day = SE(n.day), -->
<!--                                    #mean.n.day.all = mean(n.day.all), -->
<!--                                    #SE.n.day.all = SE(n.day.all), -->
<!--                                    mean.n.night = mean(n.night), -->
<!--                                    SE.n.night = SE(n.night), -->
<!--                                    #mean.n.night.all = mean(n.night.all), -->
<!--                                    #SE.n.night.all = SE(n.night.all), -->
<!--                                    mean.Mass = mean(Mass_kg), -->
<!--                                    SE.Mass = SE(Mass_kg), -->
<!--                                    mean.SCL = mean(SCL_cm), -->
<!--                                    SE.SCL = SE(SCL_cm)) -> data2.by.period -->
<!-- ``` -->


<!-- Then do comparisons between pre and post for SCL, Mass, and transmission days. -->

<!-- ```{r} -->
<!-- fit.SCL <- lm(SCL_cm ~ period, data = data2) -->
<!-- summary(fit.SCL) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- fit.Mass <- lm(Mass_kg ~ period, data = data2) -->
<!-- summary(fit.Mass) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- fit.days <- lm(n.days ~ period, data = data2) -->
<!-- summary(fit.days) -->
<!-- ``` -->



