---
title: "SDB map"
output: html_notebook
---

This notebook makes the first figure - map of SDB. 

```{r message=FALSE}
rm(list = ls())

ifelse(Sys.info()[1] == 'Linux',
       source('~/Documents/R/tools/TomosFunctions.R'),
       source('~/R/tools/TomosFunctions.R'))

#library(readxl)
library(dplyr)
library(adehabitatHR)
library(rgdal)
library(leaflet) 
library(ggplot2)
library(lubridate)
library(tidyverse)
library(ggridges)
library(sf)

source("HR_analysis_fcns.R")


# internet <- F #TRUE
save.fig <- T

SDBay.gis <- spTransform(readOGR(dsn = "GISfiles",
                                 layer = "sd_bay",
                                 verbose = FALSE),
                         CRS("+proj=longlat +datum=WGS84"))

SDBay.df <- broom::tidy(SDBay.gis)

water.gis <- spTransform(readOGR(dsn = "GISfiles",
                                 layer = "water",
                                 verbose = FALSE),
                         CRS("+proj=longlat +datum=WGS84"))

water.df <- broom::tidy(water.gis)

eelgrass.2008 <- spTransform(readOGR(dsn = "GISfiles/Features",
                                 layer = "SD_Baywide_Eelgrass_2008",
                                 verbose = FALSE),
                         CRS("+proj=longlat +datum=WGS84"))
eelgrass.2008.df <- broom::tidy(eelgrass.2008)

eelgrass.2014 <- spTransform(readOGR(dsn = "GISfiles/Features",
                                 layer = "SD_Baywide_Eelgrass_2014_Final",
                                 verbose = FALSE),
                         CRS("+proj=longlat +datum=WGS84"))
eelgrass.2014.df <- broom::tidy(eelgrass.2014)

water.color <- "lavender"
#water.color <- "lightblue"
background.color <- "darkgray"
eelgrass.color <- "mediumseagreen" #"lightgreen"

#N.end <- 32.69   # approx Coronado bridge
N.end <- 32.66 # changed from 32.69 because 152314 had a gap in data points between ~32.65 and ~32.66 - seems like there was a different behavior south and north of 32.66
```


```{r}

# tagprj <- readOGR(dsn = "Tag_065_UTMzone11n", 
#                   layer = "tag_065_project")
# tagproj <- proj4string(tagprj)

box.coords <- data.frame(lon = c(-117.16, -117.09, -117.09, -117.16, -117.16),
                         lat = c(32.665, 32.665, 32.595, 32.595, 32.665))

buoy.location <- data.frame(lon = -117.173, lat = 32.713)

# box.coords %>% st_as_sf(coords = c("longitude", "latitude"),
#                         crs = 4326) %>%
#   summarise(geometry = st_combine(geometry)) %>%
#   st_cast("POLYGON") -> box.polygon

p.map.1.2008 <- ggplot() + 
  geom_polygon(data = water.df,
               aes(x = long, y = lat, group = group),
               fill = water.color,
               color = "black") +
  geom_polygon(data = SDBay.df,
               aes(x = long, y = lat, group = group),
               fill = water.color,
               color = "black") +
  geom_polygon(data = eelgrass.2008.df,
               aes(x = long, y = lat, group = group),
               fill = eelgrass.color,
               color = "darkgreen") +
  geom_polygon(data = box.coords,
               aes(x = lon, y = lat),
               color = "black",
               size = 1.2,
               fill = NA) + 
  geom_point(data = buoy.location,
             aes(x = lon, y = lat),
             color = "firebrick2",
             size = 3) + 
  coord_map(ylim = c(32.57, 32.75),
            xlim = c(-117.27, -117.08)) + 
  ggsn::scalebar(transform = TRUE,
                 model = "WGS84",
                 dist_unit = "km", 
                 dist = 2,
                 height = 0.1,
                 st.size = 4,
                 st.dist = 0.15,
                 x.min = -117.25,
                 x.max = -117.20,
                 y.min = 32.58,
                 y.max = 32.61) +
  labs(x = "", y = "")+ 
  theme(panel.border = element_rect(color = "black", fill = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = background.color,
                                        colour = background.color),
        axis.text = element_text(size = 12))  

if (save.fig)
  ggsave(plot = p.map.1.2008,
         filename = "figures/SanDiegoBay_Figure1_2008.png",
         device = "png",
         dpi = 600)

p.map.1.2008
```

```{r}
p.map.1.2014 <- ggplot() + 
  geom_polygon(data = water.df,
               aes(x = long, y = lat, group = group),
               fill = water.color,
               color = "black") +
  geom_polygon(data = SDBay.df,
               aes(x = long, y = lat, group = group),
               fill = water.color,
               color = "black") +
  geom_polygon(data = eelgrass.2014.df,
               aes(x = long, y = lat, group = group),
               fill = eelgrass.color,
               color = "darkgreen") +
  geom_polygon(data = box.coords,
               aes(x = lon, y = lat),
               color = "black",
               size = 1.2,
               fill = NA) + 
   geom_point(data = buoy.location,
             aes(x = lon, y = lat),
             color = "firebrick2",
             size = 3) + 
  coord_map(ylim = c(32.57, 32.75),
            xlim = c(-117.27, -117.08)) + 
  labs(x = "", y = "")+ 
  theme(panel.border = element_rect(color = "black", fill = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = background.color,
                                        colour = background.color),
        axis.text = element_text(size = 12 ))  

if (save.fig)
  ggsave(plot = p.map.1.2014,
         filename = "figures/SanDiegoBay_Figure1_2014.png",
         device = "png",
         dpi = 600)

p.map.1.2014
```





