---
title: "UD table"
output: html_notebook
---

Creates Table 3 of the manuscript summarizing estimated individual UDS.

```{r}
rm(list = ls())

ifelse(Sys.info()[1] == 'Linux',
       source('~/Documents/R/tools/TomosFunctions.R'),
       source('~/R/tools/TomosFunctions.R'))

#library(readxl)
library(dplyr)
library(leaflet) 
library(lubridate)
library(tidyverse)

source("HR_analysis_fcns.R")

SDBay.gis <- spTransform(readOGR(dsn = "GISfiles",
                                           layer = "sd_bay",
                                           verbose = FALSE),
                                   CRS("+proj=longlat +datum=WGS84"))

SDBay.df <- broom::tidy(SDBay.gis)
water.color <- "lightblue"
background.color <- "darkgray"

# this file was created in PreVsPostAnalysis_DayNight.Rmd
all.data.frames <- readRDS(file = "RData/PreVsPost_DayNight.RDS")

UD.eachID.pre.combined <- all.data.frames$UD.eachID.pre.daynight 
UD.eachID.post.combined<- all.data.frames$UD.eachID.post.daynight 
UD.eachID.pre.day <- all.data.frames$UD.eachID.pre.day 
UD.eachID.pre.night <- all.data.frames$UD.eachID.pre.night 
UD.eachID.post.day <- all.data.frames$UD.eachID.post.day 
UD.eachID.post.night <- all.data.frames$UD.eachID.post.night
UD.post.95.latlon <- all.data.frames$UD95.allID.post.daynight 
UD.post.50.latlon <- all.data.frames$UD50.allID.post.daynight 
UD.pre.95.latlon <- all.data.frames$UD95.allID.pre.daynight 
UD.pre.50.latlon <- all.data.frames$UD50.allID.pre.daynight 
UD.pre.day.95.latlon <- all.data.frames$UD95.allID.pre.day 
UD.pre.day.50.latlon <- all.data.frames$UD50.allID.pre.day
UD.pre.night.95.latlon <- all.data.frames$UD95.allID.pre.night
UD.pre.night.50.latlon <- all.data.frames$UD50.allID.pre.night 
UD.post.day.95.latlon <- all.data.frames$UD95.allID.post.day
UD.post.day.50.latlon <- all.data.frames$UD50.allID.post.day 
UD.post.night.95.latlon <- all.data.frames$UD95.allID.post.night 
UD.post.night.50.latlon <- all.data.frames$UD50.allID.post.night
UD.pre.day.night.95.latlon <- all.data.frames$UD95.allID.pre.day.night
UD.pre.day.night.50.latlon <- all.data.frames$UD50.allID.pre.day.night
UD.post.day.night.95.latlon <- all.data.frames$UD95.allID.post.day.night
UD.post.day.night.50.latlon <- all.data.frames$UD50.allID.post.day.night
```

What we want for the table are in separate dataframes...

Pre - Day
```{r}
dat <- UD.eachID.pre.day$area
dat
summary(dat)
sd(dat$area.50)/sqrt(nrow(dat))
sd(dat$area.95)/sqrt(nrow(dat))


```

Pre - Night
```{r}
dat <- UD.eachID.pre.night$area
sdat
summary(dat)
sd(dat$area.50)/sqrt(nrow(dat))
sd(dat$area.95)/sqrt(nrow(dat))


```

Pre - Day + Night
```{r}
dat <- UD.eachID.pre.combined$area
dat
summary(dat)
sd(dat$area.50)/sqrt(nrow(dat))
sd(dat$area.95)/sqrt(nrow(dat))


```

Post - Day
```{r}
dat <- UD.eachID.post.day$area
dat
summary(dat)
sd(dat$area.50)/sqrt(nrow(dat))
sd(dat$area.95)/sqrt(nrow(dat))

```

Pre - Night
```{r}
dat <- UD.eachID.post.night$area
dat
summary(dat)
sd(dat$area.50)/sqrt(nrow(dat))
sd(dat$area.95)/sqrt(nrow(dat))

```

Pre - Day + Night
```{r}
dat <- UD.eachID.post.combined$area
data.frame(dat)
summary(dat)
sd(dat$area.50)/sqrt(nrow(dat))
sd(dat$area.95)/sqrt(nrow(dat))

```


